language: python

cache:
  directories:
    - $HOME/.cache/pip

sudo: true
dist: xenial

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

install:
  - pip install tox

script:
  - tox
